# Generated by Django 5.0.6 on 2024-06-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='addr',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
