# Generated by Django 5.0.6 on 2024-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_category_addr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='addr',
        ),
    ]
