# Generated by Django 5.0.6 on 2024-06-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_category_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='addr',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='addr2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='addr3',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
